In [4]:
import pandas as pd
import basketball_reference_rodrixx as brr

In [5]:
getter = brr.BasketballReferenceGetter()

In [6]:
df_modelling = getter.extract_player_stats_multiple('1982-2022', mvp = True, advanced = True, ranks = True)

In [7]:
df_modelling.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP_pg,FG_pg,FGA_pg,...,DBPM_rank,BPM_rank,VORP_rank,%W,GT,%W_rank,%G,Votes,Share,MaxVotes
0,1,Kareem Abdul-Jabbar,C,34,LAL,76,76,35.2,9.9,17.1,...,20,5,8,0.695,82,3,0.927,31,0.045,690
1,2,Alvan Adams,C,27,PHO,79,75,30.3,6.4,13.0,...,10,13,15,0.561,82,10,0.963,0,0.000,690
2,3,Mark Aguirre,SF,22,DAL,51,20,28.8,7.5,16.1,...,48,34,36,0.341,82,36,0.622,0,0.000,690
3,4,Danny Ainge,SG,22,BOS,53,1,10.6,1.5,4.2,...,22,68,47,0.768,82,1,0.646,0,0.000,690
4,5,Tiny Archibald,PG,33,BOS,68,51,31.9,4.5,9.6,...,45,40,35,0.768,82,1,0.829,0,0.000,690

In [8]:
df_modelling.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21747 entries, 0 to 21746
Data columns (total 138 columns):
 #    Column        Dtype
---   ------        -----
 0    Rk            int64
 1    Player        object
 2    Pos           object
 3    Age           int64
 4    Tm            object
 5    G             int64
 6    GS            int64
 7    MP_pg         float64
 8    FG_pg         float64
 9    FGA_pg        float64
 10   FG%           float64
 11   3P_pg         float64
 12   3PA_pg        float64
 13   3P%           float64
 14   2P_pg         float64
 15   2PA_pg        float64
 16   2P%           float64
 17   eFG%          float64
 18   FT_pg         float64
 19   FTA_pg        float64
 20   FT%           float64
 21   ORB_pg        float64
 22   DRB_pg        float64
 23   TRB_pg        float64
 24   AST_pg        float64
 25   STL_pg        float64
 26   BLK_pg        float64
 27   TOV_pg        float64
 28   PF_pg         float64
 29   PTS_pg        float64
 30   MP_rank_pg    int64
 31   FG_rank_pg    int64
 32   FGA_rank_pg   int64
 33   FG%_rank      int64
 34   3P_rank_pg    int64
 35   3PA_rank_pg   int64
 36   3P%_rank      int64
 37   2P_rank_pg    int64
 38   2PA_rank_pg   int64
 39   2P%_rank      int64
 40   eFG%_rank     int64
 41   FT_rank_pg    int64
 42   FTA_rank_pg   int64
 43   FT%_rank      int64
 44   ORB_rank_pg   int64
 45   DRB_rank_pg   int64
 46   TRB_rank_pg   int64
 47   AST_rank_pg   int64
 48   STL_rank_pg   int64
 49   BLK_rank_pg   int64
 50   TOV_rank_pg   int64
 51   PF_rank_pg    int64
 52   PTS_rank_pg   int64
 53   %GS           float64
 54   Season        int64
 55   MP_tot        int64
 56   FG_tot        int64
 57   FGA_tot       int64
 58   3P_tot        int64
 59   3PA_tot       int64
 60   2P_tot        int64
 61   2PA_tot       int64
 62   FT_tot        int64
 63   FTA_tot       int64
 64   ORB_tot       int64
 65   DRB_tot       int64
 66   TRB_tot       int64
 67   AST_tot       int64
 68   STL_tot       int64
 69   BLK_tot       int64
 70   TOV_tot       int64
 71   PF_tot        int64
 72   PTS_tot       int64
 73   MP_rank_tot   int64
 74   FG_rank_tot   int64
 75   FGA_rank_tot  int64
 76   3P_rank_tot   int64
 77   3PA_rank_tot  int64
 78   2P_rank_tot   int64
 79   2PA_rank_tot  int64
 80   FT_rank_tot   int64
 81   FTA_rank_tot  int64
 82   ORB_rank_tot  int64
 83   DRB_rank_tot  int64
 84   TRB_rank_tot  int64
 85   AST_rank_tot  int64
 86   STL_rank_tot  int64
 87   BLK_rank_tot  int64
 88   TOV_rank_tot  int64
 89   PF_rank_tot   int64
 90   PTS_rank_tot  int64
 91   PER           float64
 92   TS%           float64
 93   3PAr          float64
 94   FTr           float64
 95   ORB%          float64
 96   DRB%          float64
 97   TRB%          float64
 98   AST%          float64
 99   STL%          float64
 100  BLK%          float64
 101  TOV%          float64
 102  USG%          float64
 103  OWS           float64
 104  DWS           float64
 105  WS            float64
 106  WS/48         float64
 107  OBPM          float64
 108  DBPM          float64
 109  BPM           float64
 110  VORP          float64
 111  PER_rank      int64
 112  TS%_rank      int64
 113  3PAr_rank     int64
 114  FTr_rank      int64
 115  ORB%_rank     int64
 116  DRB%_rank     int64
 117  TRB%_rank     int64
 118  AST%_rank     int64
 119  STL%_rank     int64
 120  BLK%_rank     int64
 121  TOV%_rank     int64
 122  USG%_rank     int64
 123  OWS_rank      int64
 124  DWS_rank      int64
 125  WS_rank       int64
 126  WS/48_rank    int64
 127  OBPM_rank     int64
 128  DBPM_rank     int64
 129  BPM_rank      int64
 130  VORP_rank     int64
 131  %W            float64
 132  GT            int32
 133  %W_rank       int32
 134  %G            float64
 135  Votes         int32
 136  Share         float64
 137  MaxVotes      int32
dtypes: float64(47), int32(4), int64(84), object(3)
memory usage: 22.6+ MB

In [6]:
df_2022 = getter.extract_player_stats_multiple(2022, mvp = False, advanced = True, ranks = True)

In [7]:
df_2022.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP_pg,FG_pg,FGA_pg,...,WS_rank,WS/48_rank,OBPM_rank,DBPM_rank,BPM_rank,VORP_rank,%W,GT,%W_rank,%G
0,1,Precious Achiuwa,C,22,TOR,73,28,23.6,3.6,8.3,...,67,151,82,58,98,48,0.585,82,22,0.890
1,2,Steven Adams,C,28,MEM,76,75,26.3,2.8,5.1,...,26,62,52,42,52,26,0.683,82,3,0.927
2,3,Bam Adebayo,C,24,MIA,56,56,32.6,7.3,13.0,...,22,47,45,31,35,19,0.646,82,4,0.683
3,4,Santi Aldama,PF,21,MEM,32,0,11.3,1.7,4.1,...,89,177,104,67,128,49,0.683,82,3,0.390
4,5,LaMarcus Aldridge,C,36,BRK,47,12,22.3,5.4,9.7,...,61,84,49,58,65,39,0.537,82,37,0.573

In [8]:
df_2022.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 812 entries, 0 to 811
Data columns (total 135 columns):
 #    Column        Dtype
---   ------        -----
 0    Rk            int64
 1    Player        object
 2    Pos           object
 3    Age           int64
 4    Tm            object
 5    G             int64
 6    GS            int64
 7    MP_pg         float64
 8    FG_pg         float64
 9    FGA_pg        float64
 10   FG%           float64
 11   3P_pg         float64
 12   3PA_pg        float64
 13   3P%           float64
 14   2P_pg         float64
 15   2PA_pg        float64
 16   2P%           float64
 17   eFG%          float64
 18   FT_pg         float64
 19   FTA_pg        float64
 20   FT%           float64
 21   ORB_pg        float64
 22   DRB_pg        float64
 23   TRB_pg        float64
 24   AST_pg        float64
 25   STL_pg        float64
 26   BLK_pg        float64
 27   TOV_pg        float64
 28   PF_pg         float64
 29   PTS_pg        float64
 30   MP_rank_pg    int64
 31   FG_rank_pg    int64
 32   FGA_rank_pg   int64
 33   FG%_rank      int64
 34   3P_rank_pg    int64
 35   3PA_rank_pg   int64
 36   3P%_rank      int64
 37   2P_rank_pg    int64
 38   2PA_rank_pg   int64
 39   2P%_rank      int64
 40   eFG%_rank     int64
 41   FT_rank_pg    int64
 42   FTA_rank_pg   int64
 43   FT%_rank      int64
 44   ORB_rank_pg   int64
 45   DRB_rank_pg   int64
 46   TRB_rank_pg   int64
 47   AST_rank_pg   int64
 48   STL_rank_pg   int64
 49   BLK_rank_pg   int64
 50   TOV_rank_pg   int64
 51   PF_rank_pg    int64
 52   PTS_rank_pg   int64
 53   %GS           float64
 54   Season        int64
 55   MP_tot        int64
 56   FG_tot        int64
 57   FGA_tot       int64
 58   3P_tot        int64
 59   3PA_tot       int64
 60   2P_tot        int64
 61   2PA_tot       int64
 62   FT_tot        int64
 63   FTA_tot       int64
 64   ORB_tot       int64
 65   DRB_tot       int64
 66   TRB_tot       int64
 67   AST_tot       int64
 68   STL_tot       int64
 69   BLK_tot       int64
 70   TOV_tot       int64
 71   PF_tot        int64
 72   PTS_tot       int64
 73   MP_rank_tot   int64
 74   FG_rank_tot   int64
 75   FGA_rank_tot  int64
 76   3P_rank_tot   int64
 77   3PA_rank_tot  int64
 78   2P_rank_tot   int64
 79   2PA_rank_tot  int64
 80   FT_rank_tot   int64
 81   FTA_rank_tot  int64
 82   ORB_rank_tot  int64
 83   DRB_rank_tot  int64
 84   TRB_rank_tot  int64
 85   AST_rank_tot  int64
 86   STL_rank_tot  int64
 87   BLK_rank_tot  int64
 88   TOV_rank_tot  int64
 89   PF_rank_tot   int64
 90   PTS_rank_tot  int64
 91   PER           float64
 92   TS%           float64
 93   3PAr          float64
 94   FTr           float64
 95   ORB%          float64
 96   DRB%          float64
 97   TRB%          float64
 98   AST%          float64
 99   STL%          float64
 100  BLK%          float64
 101  TOV%          float64
 102  USG%          float64
 103  OWS           float64
 104  DWS           float64
 105  WS            float64
 106  WS/48         float64
 107  OBPM          float64
 108  DBPM          float64
 109  BPM           float64
 110  VORP          float64
 111  PER_rank      int64
 112  TS%_rank      int64
 113  3PAr_rank     int64
 114  FTr_rank      int64
 115  ORB%_rank     int64
 116  DRB%_rank     int64
 117  TRB%_rank     int64
 118  AST%_rank     int64
 119  STL%_rank     int64
 120  BLK%_rank     int64
 121  TOV%_rank     int64
 122  USG%_rank     int64
 123  OWS_rank      int64
 124  DWS_rank      int64
 125  WS_rank       int64
 126  WS/48_rank    int64
 127  OBPM_rank     int64
 128  DBPM_rank     int64
 129  BPM_rank      int64
 130  VORP_rank     int64
 131  %W            float64
 132  GT            int32
 133  %W_rank       int32
 134  %G            float64
dtypes: float64(46), int32(2), int64(84), object(3)
memory usage: 850.2+ KB

In [9]:
df_modelling.to_pickle('dataframes/stats_1982_to_2022.pkl')

In [10]:
df_2022.to_pickle('dataframes/stats_2022.pkl')